/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as IdeiasRouteImport } from './routes/ideias'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as RotinaRouteImport } from './routes/rotina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeiasRoute = IdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaRoute = RotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/financeiro': typeof FinanceiroRoute
  '/ideias': typeof IdeiasRoute
  '/metricas': typeof MetricasRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/financeiro': typeof FinanceiroRoute
  '/ideias': typeof IdeiasRoute
  '/metricas': typeof MetricasRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/financeiro': typeof FinanceiroRoute
  '/ideias': typeof IdeiasRoute
  '/metricas': typeof MetricasRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/assistente' | '/financeiro' | '/ideias' | '/metricas' | '/rotina'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistente' | '/financeiro' | '/ideias' | '/metricas' | '/rotina'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/financeiro'
    | '/ideias'
    | '/metricas'
    | '/rotina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IdeiasRoute: typeof IdeiasRoute
  MetricasRoute: typeof MetricasRoute
  RotinaRoute: typeof RotinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideias': {
      id: '/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof IdeiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina': {
      id: '/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof RotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  FinanceiroRoute: FinanceiroRoute,
  IdeiasRoute: IdeiasRoute,
  MetricasRoute: MetricasRoute,
  RotinaRoute: RotinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
